// <auto-generated />
using GoogleKeepAssignment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoogleKeepAssignment.Migrations.Notes
{
    [DbContext(typeof(NotesContext))]
    [Migration("20180801135550_collectiontoilist")]
    partial class collectiontoilist
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoogleKeepAssignment.Models.CheckList", b =>
                {
                    b.Property<string>("Title");

                    b.Property<string>("CheckListData");

                    b.Property<bool>("CheckListStatus");

                    b.HasKey("Title", "CheckListData");

                    b.ToTable("CheckList");
                });

            modelBuilder.Entity("GoogleKeepAssignment.Models.Label", b =>
                {
                    b.Property<string>("Title");

                    b.Property<string>("LabelString");

                    b.HasKey("Title", "LabelString");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("GoogleKeepAssignment.Models.Note", b =>
                {
                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("PinStatus");

                    b.Property<string>("PlainText");

                    b.HasKey("Title");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("GoogleKeepAssignment.Models.CheckList", b =>
                {
                    b.HasOne("GoogleKeepAssignment.Models.Note", "Note")
                        .WithMany("CheckLists")
                        .HasForeignKey("Title")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GoogleKeepAssignment.Models.Label", b =>
                {
                    b.HasOne("GoogleKeepAssignment.Models.Note", "Note")
                        .WithMany("Labels")
                        .HasForeignKey("Title")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
