// <auto-generated />
using GoogleKeepAssignment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoogleKeepAssignment.Migrations
{
    [DbContext(typeof(GoogleKeepContext))]
    [Migration("20180801020630_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoogleKeepAssignment.Models.CheckList", b =>
                {
                    b.Property<string>("CheckListData")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("CheckListStatus");

                    b.Property<string>("NoteTitle");

                    b.HasKey("CheckListData");

                    b.HasIndex("NoteTitle");

                    b.ToTable("CheckList");
                });

            modelBuilder.Entity("GoogleKeepAssignment.Models.Label", b =>
                {
                    b.Property<string>("LabelString")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NoteTitle");

                    b.HasKey("LabelString");

                    b.HasIndex("NoteTitle");

                    b.ToTable("Label");
                });

            modelBuilder.Entity("GoogleKeepAssignment.Models.Note", b =>
                {
                    b.Property<string>("Title")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("PinStatus");

                    b.Property<string>("PlainText");

                    b.HasKey("Title");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("GoogleKeepAssignment.Models.CheckList", b =>
                {
                    b.HasOne("GoogleKeepAssignment.Models.Note")
                        .WithMany("CheckLists")
                        .HasForeignKey("NoteTitle");
                });

            modelBuilder.Entity("GoogleKeepAssignment.Models.Label", b =>
                {
                    b.HasOne("GoogleKeepAssignment.Models.Note")
                        .WithMany("Labels")
                        .HasForeignKey("NoteTitle");
                });
#pragma warning restore 612, 618
        }
    }
}
